server:
  address: 0.0.0.0
  port: 8085

spring:
  application:
    name: service-kotlin-sample 

management:
  server:
    port: 8086
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      enabled: true
    httptrace:
      enabled: true
    jolokia:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    org.apache.qpid.jms.sasl.SaslMechanismFinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- %logger : %replace(%m){'[\r\n]', ''}%n%wEx"
